name: Update Data and Deploy to GitHub Pages

on:
    schedule:
        - cron: "*/10 * * * *"

permissions:
    contents: write
    pages: write

jobs:
    update_and_deploy:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Step 2: Set up Python
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            # Step 3: Install dependencies
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r fb-scraper/requirements.txt

            # Step 5: Run the Python script to fetch data
            - name: Fetch data from scraper
              run: python fb-scraper/scrapeboard.py

            # Step 6: Commit and push the updated data.json to GitHub
            - name: Commit and push updated data.json
              run: |
                  git config --global user.name 'SamratAdhikari'
                  git config --global user.email 'samratmetaladhikari@gmail.com'
                  git add public/data.json
                  git commit -m 'Update data.json with new posts data'
                  git push